spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mySpring
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: duatmdqja09

  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        show-sql: true

server:
  servlet:
    encoding:
      force-response: true

