spring:
  datasource:
    url: jdbc:mysql://database-1.ct4cqg6q4lkm.ap-northeast-2.rds.amazonaws.com:3306/dockertest
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: admin
    password: duatmdqja09
  jpa:
    hibernate:
      ddl-auto: create


cloud:
  aws:
    s3:
      bucket: ${{ secrets.S3BUCKET }}
    credentials:
      access-key: ${{ secrets.S3KEY }}
      secret-key: ${{ secrets.S3SECRETKEY }}
    region:
      static: ${{ secrets.S3REGION }}
      auto: false
    stack:
      auto: false